"txtHhksNo1": mojimoji.zen_to_han(kysh.hiho[0]),
"txtHhksNo2": mojimoji.zen_to_han(kysh.hiho[1]),
"txtHhksNo3": mojimoji.zen_to_han(kysh.hiho[2]),
"cmbStk": kysh.kubun,
"txtFuriganaKatakana1": (mojimoji.han_to_zen(kysh.name_kana[0]) + ' ' + mojimoji.zen_to_han(kysh.name_kana[1])),
"txtHhksNameKnj": (mojimoji.zen_to_han(kysh.name_kana[0]) + ' ' + mojimoji.zen_to_han(kysh.name_kana[1])),
"txtFuriganaKatakana2": "",
"txtHkgoNoNameKnj": "",
"cmbSeibetsu": kysh.sex,
"seinengappiGG": (mojimoji.zen_to_han(kysh.birth[0])),
"seinengappiYY": (mojimoji.zen_to_han(kysh.birth[1])),
"seinengappiMM": (mojimoji.zen_to_han(kysh.birth[2])),
"seinengappiDD": (mojimoji.zen_to_han(kysh.birth[3])),
"txtJgshNo1": (mojimoji.zen_to_han(jygs.kohonum[0])),
"txtJgshNo2": (mojimoji.zen_to_han(jygs.kohonum[1])),
"txtJgshNo3": (mojimoji.zen_to_han(jygs.kohonum[2])),
"cmbHhksToNattakotoNoGenin": "4",
"cmbChgnShiharaiNoTaiyo": "1",
"txtChgnChgnGetsugaku": str(int(kysh.tin)),
"skkuStkYmdGG": (mojimoji.zen_to_han(kysh.getdate[0])),
"skkuStkYmdYY": (mojimoji.zen_to_han(kysh.getdate[1])),
"skkuStkYmdMM": (mojimoji.zen_to_han(kysh.getdate[2])),
"skkuStkYmdDD": (mojimoji.zen_to_han(kysh.getdate[3])),
"cmbKoyoKeitai": "7",
"cmbSksu": "05",
"cmbShusyokuKeiro": "4",
"txt1ShuukanNoShoteiRodoJnJn": "40",
"txt1ShuukanNoShoteiRodoJnFun": "00",
"keiyakuKikanNoSdamStaGG": "",
"keiyakuKikanNoSdamStaYY": "",
"keiyakuKikanNoSdamStaMM": "",
"keiyakuKikanNoSdamStaDD": "",
"keiyakuKikanNoSdamEndGG": "",
"keiyakuKikanNoSdamEndYY": "",
"keiyakuKikanNoSdamEndMM": "",
"keiyakuKikanNoSdamEndDD": "",
"rdoKeiyakuKikanNoSdamJokoUmu": "",
"rdoKeiyakuKikanNoSdam": "2",
"txtJgshMei": (mojimoji.han_to_zen(jygs.name)),
"txtBiko": (mojimoji.han_to_zen(kysh.bikou)),
"txtHhksNameRomaji": "",
"txtZairyuCardNo": "",
"bikoZairyuKikanYY": "",
"bikoZairyuKikanMM": "",
"bikoZairyuKikanDD": "",
"rdoBikoSkkuGaiKyokaUmu": "",
"cmbHakenUkeoiShuroukbn": "",
"txtBikoKokuseki": "",
"txtBikoZairyuSkku": "",
"txtJgysJusho": (mojimoji.han_to_zen(jygs.address)),
"txtJgysName": (mojimoji.han_to_zen(jygs.name)),
"txtJgysTel1": (mojimoji.zen_to_han(jygs.phone[0])),
"txtJgysTel2": (mojimoji.zen_to_han(jygs.phone[1])),
"txtJgysTel3": (mojimoji.zen_to_han(jygs.phone[2])),
"todokedeYmdYY": "",
"todokedeYmdMM": "",
"todokedeYmdDD": "",
"txtShinseiSaki": "新宿",
"shakaiRomushiSkseYmdGG": "",
"shakaiRomushiSkseYmdYY": "",
"shakaiRomushiSkseYmdMM": "",
"shakaiRomushiSkseYmdDD": "",
"txtShakaiRomushiDairiSha": "",
"txtShakaiRomushiName": "",
"txtShakaiRomushiTel1": "",
"txtShakaiRomushiTel2": "",
"txtShakaiRomushiTel3": "",
"commonDownload": "帳票作成",
"screenId": "001050",
"action": "",
"codeAssistType": "",
"codeAssistKind": "",
"codeAssistCode": "",
"codeAssistItemCode": "",
"codeAssistItemName": "",
"codeAssistDivide": "",
"maba_vrbs": "continueMakeButton,commonDownload",
"preCheckFlg": "false"

"txtHhksNo1":mojimoji.zen_to_han(kysh.hiho[0]),
            "txtHhksNo2":mojimoji.zen_to_han(kysh.hiho[1]),
            "txtHhksNo3":mojimoji.zen_to_han(kysh.hiho[2]),
            "cmbStk":kysh.kubun,
            "txtFuriganaKatakana1":(mojimoji.han_to_zen(kysh.name_kana[0]) + ' ' + mojimoji.zen_to_han(kysh.name_kana[1])),
            "txtHhksNameKnj":(mojimoji.zen_to_han(kysh.name_kana[0]) + ' ' + mojimoji.zen_to_han(kysh.name_kana[1])),
            "cmbSeibetsu":kysh.sex,
            "seinengappiGG":(mojimoji.zen_to_han(kysh.birth[0])),
            "seinengappiYY":(mojimoji.zen_to_han(kysh.birth[1])),
            "seinengappiMM":(mojimoji.zen_to_han(kysh.birth[2])),
            "seinengappiDD":(mojimoji.zen_to_han(kysh.birth[3])),
            "txtJgshNo1":(mojimoji.zen_to_han(jygs.kohonum[0])),
            "txtJgshNo2":(mojimoji.zen_to_han(jygs.kohonum[1])),
            "txtJgshNo3":(mojimoji.zen_to_han(jygs.kohonum[2])),
            "cmbHhksToNattakotoNoGenin":'4',
            "cmbChgnShiharaiNoTaiyo":'1',
            "txtChgnChgnGetsugaku":str(int(kysh.tin)),
            "skkuStkYmdGG":(mojimoji.zen_to_han(kysh.getdate[0])),
            "skkuStkYmdYY":(mojimoji.zen_to_han(kysh.getdate[1])),
            "skkuStkYmdMM":(mojimoji.zen_to_han(kysh.getdate[2])),
            "skkuStkYmdDD":(mojimoji.zen_to_han(kysh.getdate[3])),
            "cmbKoyoKeitai":'7',
            "cmbSksu":'5',
            "cmbShushokuKeiro":'4',
            "txt1ShuukanNoShoteiRodoJnJn":"40",
            "txt1ShuukanNoShoteiRodoJnFun":"00",
            "rdoKeiyakuKikanNoSdam":"2",
            "txtJgshMei":(mojimoji.han_to_zen(jygs.name)),
            "txtBiko":(mojimoji.han_to_zen(kysh.bikou)),
            "txtJgshJusho":(mojimoji.han_to_zen(jygs.address)),
            "txtJgshTel1":(mojimoji.zen_to_han(jygs.phone[0])),
            "txtJgshTel2":(mojimoji.zen_to_han(jygs.phone[1])),
            "txtJgshTel3":(mojimoji.zen_to_han(jygs.phone[2])),
            "txtShinseiSaki":"新宿",
            "commonDownload": "帳票作成",
            "screenId": "001050",
            "action": "",
            "codeAssistType": "",
            "codeAssistKind": "",
            "codeAssistCode": "",
            "codeAssistItemCode": "",
            "codeAssistItemName": "",
            "codeAssistDivide": "",
            "maba_vrbs": "continueMakeButton,commonDownload",
            "preCheckFlg": "false"